### ISSUE TITLE
Translate cover page for Chinese Release PDF

### ISSUE THREAD

**Issue by yash2002109** [chaoss/translations#101]
Currently, MARS uses the English cover page for Chinese translations as well. It would be great if we could translate the cover page.

Chinese Cover Page: https://github.com/chaoss/MARS/blob/main/automation/active_user_input/chinese_cover.tex

Additionally, the English report will only be having the latest release notes starting this release. Since this is the first time that we are releasing the translations for Chinese, I do **not** think that we need to create a file for that.

Does anyone have any thoughts on this?

**Comment by eyehwan** [comment]
Hi,

I would take care of the cover page translation.

Maybe we can only translate the latest release notes the same as the
English report? Does it make sense?

BR//Yehui.

**Comment by eyehwan** [comment]
Hi @yash2002109 , may I know which part in https://github.com/chaoss/MARS/blob/main/automation/active_user_input/chinese_cover.tex should I translate? Only No. 13 line  "Release 2021-03"?

**Comment by yash2002109** [comment]
Hi @eyehwan,

I think there are only two words that require translation `metrics` on line 9 and `release` on line 13. 

Considering that there are only two words, I don't know if we should even translate them or leave them as it is.

I would appreciate your opinion on this!

**Comment by yash2002109** [comment]
Here is the preview of the current cover page:

![image](https://user-images.githubusercontent.com/77677278/134617558-5212e01f-2151-4441-8c53-312c04fc4909.png)

**Comment by eyehwan** [comment]
Hi, I just push code review https://github.com/chaoss/MARS/pull/49

For the release notes, I also don't think we need create another translation at this time.
