### ISSUE TITLE
Update MARS YAML file for Chinese metric translations

### ISSUE THREAD

**Issue by yash2002109** [chaoss/translations#102]
Since the Chinese translations for the metrics belonging to the current release cycle are complete. We can now proceed to update the YAML file for MARS.

Chinese YAML file: https://github.com/chaoss/MARS/blob/main/automation/active_user_input/chinese_working-groups-config.yml

Refer to this [README](https://github.com/chaoss/MARS/blob/main/automation/active_user_input/README.md) for details about updating the YAML file.

**Please make sure all edits made to the metrics are accommodated. _Some metrics may be edited following the review period_**

**Comment by klumb** [comment]
Yes, the YAML can be updated. This is not the final signal though. Following the metrics review period, some of the metrics candidates will be edited. The translations won’t be complete until those edits are translated.
