### ISSUE TITLE
Metric Name Change - Evolution - code changes commits/ code development activity

### ISSUE THREAD

**Issue by klumb** [chaoss/translations#106]
PR: https://github.com/chaoss/wg-evolution/pull/422 

This edit is not part of the review cycle.

**Translation Teams - Please remove your language label when the task is complete.**

_The issue can be closed when all translations are done and labels are removed._

**Comment by eyehwan** [comment]
duplicated by https://github.com/chaoss/translations/issues/115, I will close this issue.
