### ISSUE TITLE
Organize the metric files into focus-areas and Add images

### ISSUE THREAD

**Issue by yash2002109** [chaoss/translations#11]
Hi everyone,

I was looking at the translated markdown files of the repository. I noticed that the images required for the display of metrics were not present.
I was thinking of adding an `images` folder in each directory containing translated markdown files. Since the names of the images and the syntax to incorporate them are in English, it shouldn't be a problem to correctly identify the required images from each working group repository and compile them into a common folder.

Please let me know your thoughts and suggestions on this.

**Comment by klumb** [comment]
Hi @yash2002109.  I think that is a good idea.

**Comment by yash2002109** [comment]
Hi @klumb, Should I also classify the translated metrics as per their focus areas and create separate folders for each focus area in the working group directory?
This will help people easily find the metrics markdown files even when their numbers increase.

**Comment by klumb** [comment]
I think this is a good idea as well. 

What do you think?
@germonprez 
@king-gao
@xiaoya-Esther

**Comment by xiaoya-Esther** [comment]
Hi @yash2002109 , thanks for the suggestion!

**Comment by yash2002109** [comment]
Hi @xiaoya-Esther, I actually meant that we do not have folders classifying the metrics as per their focus areas,

 For example, the [translations/chinese/wg-common](https://github.com/chaoss/translations/tree/main/chinese) folder has the markdown files stored commonly. I was thinking of further dividing them into subfolders for each focus area and then adding the images there.

Please refer to this [wg-common/focus-areas](https://github.com/chaoss/wg-common/tree/master/focus-areas).I was thinking that we could have a similar structure for the translations too.

**Comment by xiaoya-Esther** [comment]
Yes, I see what you mean now. Thanks @yash2002109, it's a good idea to make it more structured, please reach out anytime if you need help!

**Comment by king-gao** [comment]
I think that really super helpful for us.
