### ISSUE TITLE
Which release version of CHAOSS metrics that translations is upon on? 

### ISSUE THREAD

**Issue by eyehwan** [chaoss/translations#19]
Current layout and contents of [tranlations ](https://github.com/chaoss/translations/tree/main/chinese/wg-evolution) is behind with [CHAOSS English version](https://github.com/chaoss/wg-evolution), (taking evolution for example, others wgs are the same).

Do we have any "anchor" or declarations that our first release of translations is based on the latest release-2021-03 or any upcoming release?
Because it is kinda weired that first translations is upon an old version, specifically we have revised version of some metrics definations.

**Comment by germonprez** [comment]
Hi @eyehwan Thanks for pointing this out. I think this highlights a challenge with translations. We had to do a bulk translation at some point -- which is what you are seeing. I think that we had suggested that translations are a version behind but this seems a bit odd. Do you have thoughts on this?

**Comment by klumb** [comment]
Thanks @eyehwan 

We are working on the process of translating, maintaining, and releasing the metrics translations.

As you point out, we do need a way to connect or anchor the translated metrics to metric releases to ensure that they remain up-to-date with the current release. 

As @germonprez pointed out, so far we have just paid a company to do bulk translations. We have discussed continuing this process for new metrics to reduce the burden on the community but this does not cover maintainance. 

We will likily need to rely on our community to maintain and update the metrics translations. This process hasn't been established yet.

Your thoughts on how we can do this would be appreciated

**Comment by eyehwan** [comment]
Thanks for @germonprez  and @klumb 's update. 

Do we have a "code freeze time" before normal release? I was looking through the chapter [chaoss-metric-release](https://handbook.chaoss.community/community-handbook/community-initiatives/metrics/chaoss-metric-release) of hand book, it looks like the process in the "**1 month +1 week before release**" is similar with "code freeze time", but without any clear rules as below (just for example , referring from LF projects):
Within this time slot, no big feature(e.g. add/remove/definitions-modified metrics) was allowed, only minor bug fix (e.g. typos corrections in Metrics) or UT to increase test coverageare allowed. 

I am thinking that if we can utilize this code freeze time slot to let translations catch up with upcoming normal release, then we can celebrate them both on the release day.
The first release of up-to-date translations would need much more time than following releases, so the code freeze time at the first time we could set a little bit longer -- 6 or 8 weeks? After first release, we could set it back to a normal value like 3 weeks.

In addtion, if work load was so heavy and it was impossible to make it happen finishing the whole translations before normal release, could we consider only picking up a subset of focus areas metrics at the first release?
