### ISSUE TITLE
the translation of metrix License_Declared has some accuracy issue and grammatical errors

### ISSUE THREAD

**Issue by robekeane** [chaoss/translations#3]
License is always a very challenging topic in open source compliance, so the accuracy in translation becomes especially important.

for an example, the words in "...This can include both **software and documentation source files**. "  may cause confusion - in chinese you can translate it into  **software source files and documentation source files** or **software itself (maybe executables/codes etc.) and documentation source files**. 

I think we should make these words more faithful to original ones in Chinese.

**Comment by germonprez** [comment]
Yes! I think it is great to find the proper language that could be used here.
