### ISSUE TITLE
[new idea]Shall we maintain a list of terminology?

### ISSUE THREAD

**Issue by king-gao** [chaoss/translations#5]
When I was translating, I found some of english words are hard to translate.So  I propose we can maintain a list of terminology.  
In the list we needn't to translate the word into chinese. for example: issue , PR , repo , CHAOSS,  etc.

what's your opinion?

**Comment by germonprez** [comment]
I also like this idea. I think this could be included in the community handbook. @jaskiratsingh2000 what do you think?

**Comment by king-gao** [comment]
I agree with @germonprez perspective, we can put the list in the hand book. 
because when we talk in chinese, we also use these words directly and not translate into chinese :)

**Comment by jaskiratsingh2000** [comment]
Hi @germonprez and @king-gao Thank you very much for raising this idea and I really appreciate that. I already wrote the CHAOSS Terminology in the community handbook which can be found here https://handbook.chaoss.community/community-handbook/about/terminology
This includes:
* CHAOSS Specific Terms
* CHAOSS Committee Terms
* CHAOSS Working Group Terminology
* CHAOSS Community Mentorship Terminology

Any more suggestions are highly appreciable. Thanks!

**Comment by king-gao** [comment]
thanks @jaskiratsingh2000 for your exellent job.   
In addition to these terminology, shall we add a new list of daily language that does not require translation into chinese?
shall we put this list in chinese handbook in the future? I don't think this list is needed in the English version :)

**Comment by jaskiratsingh2000** [comment]
Yes, definitely! BTW I am bit curious to know if we have a Chinese version
of this handbook?

**Comment by king-gao** [comment]
we don't have the chinese handbook yet, but I think we can do it later :)

**Comment by jaskiratsingh2000** [comment]
Sure! That would be great.

**Comment by xiaoya-Esther** [comment]
The terminology list will be placed in the source code as the [comparison-table](https://github.com/chaoss/translations/blob/main/chinese/english-chinese-comparison-table.md)
