### ISSUE TITLE
[Glossary] Uniform translation of terminologies 

### ISSUE THREAD

**Issue by xiaoya-Esther** [chaoss/translations#9]
Below is the list of frequently occurred terminologies, we should make those expressions consistent with all the metrics:
- Common working group - 基础指标工作组
- Time to first response - 初次响应时长
- First contributor - 初次贡献者
- 解决的问题 - 关闭的issue
- new issue - 新打开issue
- comment - 评论 （原翻译中为注释）

**Comment by king-gao** [comment]
- Common working group - 常用指标工作组，the follow is my perspective:
shall we translate into"基础指标工作组"，因为常用对应的意思是其他的指标是不常用的，我担心会有歧义。

**Comment by xiaoya-Esther** [comment]
Agree!  I've changed the expression.
