### ISSUE TITLE
Remove '关注领域:' from README headings in chinese/wg-evolution

### ISSUE THREAD

**Issue by yash2002109** [chaoss/translations#97]
The READMEs for each focus-area in `chinese/wg-evolution` has the headings in the format

` # 关注领域: <focus-area-name>`
Example - https://github.com/chaoss/translations/blob/main/chinese/wg-evolution/focus-areas/code-development-efficiency/README.md

As per my understanding, `关注领域` stands for `focus area` and is not required to be present in the headings

The headings should be in the format

`# <focus-area-name>` 

Refer to the template for details: https://github.com/chaoss/community/blob/master/templates/focus-areas.md#template-for-wgfocus-areasfocus-area-namereadmemd

**Comment by xiaoya-Esther** [comment]
Solved
